#!/usr/bin/env bash

# Train model on Metacentrum infrastructure
# Arguments: git branch, model name, walltime

# Builds on: https://github.com/bakajstep/KNN_Project2024/blob/main/metacetrum_scripts/test.sh
# Which in turn builds on: https://github.com/roman-janik/diploma_thesis_program/blob/main/ner/start_training_ner.sh

GIT_BRANCH="${1:-master}"
WALLTIME="$2"
BATCH_SIZE="$3"
MODEL_PATH="$4"
GENS="$5"
MUTATION_PROB="$6"
OPTIMIZER_PATH="$7"
SCHEDULER_PATH="$8"

ARG_STRING=GIT_BRANCH="$GIT_BRANCH",BATCH_SIZE="$BATCH_SIZE",MODEL_PATH="$MODEL_PATH"
ARG_STRING+=,DOWNLOAD_DATASET=True,GENS="$GENS",MUTATION_PROB="$MUTATION_PROB",WALLTIME="$WALLTIME"
ARG_STRING+=,OPTIMIZER_PATH="$OPTIMIZER_PATH",SCHEDULER_PATH="$SCHEDULER_PATH"

# -v list of environment variables to be given to the job
qsub -v "$ARG_STRING" \
  -l walltime="$WALLTIME" ./"$(dirname "$0")"/evolve_job